apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-main
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: multicluster/second-layer
    repoURL: 'https://github.com/dgpMakes/gitops-day2'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
