apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-main
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'https://github.com/dgpMakes/gitops-day2'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default