apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/dgpmakes/java-helm'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-quarkus-obs-dev.yaml
  sources: []
  project: default
