# Not necessary if using the openshift gitops default argoCD
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
labels:
  argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
